### ISSUE TITLE
ADMB not found

### ISSUE THREAD

**Issue by pfrater** [admb-project/adstudio#2]
Hi Arni,

I'm trying to setup ADstudio in Ubuntu 16.04. I've downloaded and have been successfully running examples with ADMB. I've also downloaded and unzipped the .zip file for adstudio, and added the Emacs configuration to ~/.emacs. However, when I try to open Emacs I get the following error message:

    Warning (initialization): An error occurred while loading `~/.emacs':

    File error: Cannot open load file, no such file or directory, admb

    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file.  Start Emacs with
    the `--debug-init' option to view a complete error backtrace.

When I run `emacs --debug-init` I get the following:

     Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "admb")
       require(admb)
       eval-buffer(#<buffer  *load*> nil "~/.emacs" nil t)  ; Reading at buffer position 15899
       load-with-code-conversion("~/.emacs" "~/.emacs" t t)
       load("~/.emacs" t t)
       command-line()
       normal-top-level()

Any ideas what I might be doing wrong?

Note, I am not an experienced Emacs user.

**Comment by arni-magnusson** [comment]
Hi Paul,

Thanks for the feedback. It sounds like Emacs cannot find the `admb.el` (or `admb.elc`) file. I recommend putting it inside a directory `~/emacs/lisp/admb`, since the `.emacs` file searches recursively through everything inside `~/emacs/lisp`.

The `admb.el` file (https://github.com/admb-project/admb/blob/master/contrib/emacs/admb.el) also comes with some configuration tips in the header comments, but just putting it inside `~/emacs/lisp/admb` should do the trick.

Other Emacs packages (tmb-mode, ESS, AucTeX) should also be installed, one way or another.

Hope this helps,
Arni
